### PR TITLE
more instructions for setup

### PR DESCRIPTION
**Pull request by neoalienson**

### CODE REVIEW

**Comment by madoublet** [comment]
Thanks!  That is definitely more complete.  I plan to remove the gulp, npm, and composer requirements for production.  But, they will still be required for development.

**Comment by neoalienson** [comment]
Hi Matthew,

The composer packages are checked in under api/vendor in respond 5. It
would be better to keep composer and npm commands as these commands
download required packages from repositories, so that you don't have to
include third-party source in github repository. This keep the git clone
size small and helps to maintain package versions. The same goes for gulp
and type script, but the size is relatively smaller.

Regards,
Neo

**Comment by madoublet** [comment]
In earlier versions, I left those out of source control.  However, this caused a bunch of installation issues with devs who were unfamiliar with the command line or did not have access to it.  So, I opted to include. Perhaps, a build step to generate a zip might make sense for Respond 6.  But, I have not researched that yet.

**Comment by neoalienson** [comment]
I can setup travis ci with docker images on various platform for running
test setup steps. https://docs.travis-ci.com/user/docker/ . Let me try to
set it up and you can decide whether it would be helpful.

**Pull request merged**
